/*
    D'Jaine Brown

    stockTrade.cpp

    To calculate the gains/losses generated by a stock investment...
    ...after buying and selling shares on the stock market through...
    ...the iTrade online broker platform.

    Input:
            Company Name & Symbol
            Number of shares transacted
            Cost per share at the time of buying
            Market Value Price at the time of selling

    Processing:
           1. Declare and Initialize constants and variables
           2. Prompt user for input
           3. Run the necessary calculations
           4. Display the results

    Output:
            Total cost
            Total proceeds
            Commission Paid
            Gains/Losses (amount & percentage)

*/

// Header Files

#include <iostream>
#include <string>

using namespace std;

int main()
{
    // CONTANTS & Variables
    const double iTRADE_COM(0.02);
    long double buyPrice, sellPrice, totalCost, totalProceeds, commission, gainsOrLosses, glPercentage;
    string companyName, symbol;
    int numShares;

    // Intro
    cout << "Stock Investment Performance Calculator ..." << endl;

    // Prompt the user for the company name (no spaces)
    cout << "\nPlease enter the company name (No Spaces): ";
    cin >> companyName;

    cout << "\nPlease enter the company symbol: ";
    cin >> symbol;

    // Prompt the user for the number shares transacted
    cout << "\nPlease enter the number of shares transacted: ";
    cin >> numShares;

    // Prompt the user for the cost per share at time of purchase
    cout << "\nWhat was the cost per share at the time of purchase?" << endl << "$";
    cin >> buyPrice;

    // Prompt the user for the cost per share at time of selling
    cout << "\nWhat was the price per share at the time of selling?" << endl << "$";
    cin >> sellPrice;


    // Calculate the total cost and total proceeds
    totalCost = numShares * buyPrice;
    totalProceeds = numShares * sellPrice;

    // Calculate the commission paid (2% of totalProceeds)
    commission = iTRADE_COM * totalProceeds;

    // Calculate the gains or losses generated and their percentages
    gainsOrLosses = totalProceeds - totalCost - commission;
    glPercentage = (gainsOrLosses / totalCost) * 100;


    // Display the transaction summary
    cout << "\nTransaction Summary for " << companyName << " (" << symbol << "):\n";
    cout << "----------------------------------------\n";
    cout << "Total Cost:\t $" << totalCost << endl;
    cout << "Total Proceeds:\t $" << totalProceeds << endl;
    cout << "Commission Paid: $" << commission << endl;
    cout << "Gains/Losses:\t $" << gainsOrLosses << " (" << glPercentage << "%)\n";

    return 0;
}
